AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bot-core
  Sample SAM Template for bot-core

Globals:
  Function:
    Timeout: 300

Parameters:
  Environment:
    Type: String

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        AllowCredentials: '''*'''
        AllowMethods: '''*'''

  BotCore:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ["", ["bot-", !Ref Environment, "-botcore"]]
      CodeUri: handler_function/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-1:293854028872:layer:layer_postgre_prod:4
      Architectures:
        - x86_64
      Events:
        BotCore:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /bot_core
            Method: post
  
  SignIn:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ["", ["bot-", !Ref Environment, "-signin"]]
      CodeUri: signin/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-1:293854028872:layer:layer_postgre_prod:4
      Architectures:
        - x86_64
      Events:
        BotCore:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /signin
            Method: post
  
  LogIn:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ["", ["bot-", !Ref Environment, "-login"]]
      CodeUri: login/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-1:293854028872:layer:layer_postgre_prod:4
      Architectures:
        - x86_64
      Events:
        BotCore:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /login
            Method: post

  ValidateMail:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ["", ["bot-", !Ref Environment, "-validatemail"]]
      CodeUri: validate_mail/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-1:293854028872:layer:layer_postgre_prod:4
      Architectures:
        - x86_64
      Events:
        BotCore:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApi
            Path: /validatemail
            Method: post